/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <pwd.h>
#include <sys/types.h>
#include <stdlib.h>
//#include "userlookup.h"

int
l_byname(char* name ) {
	struct passwd *pw;
	static int result;
	pw = getpwnam( name );
	if (pw==NULL) {
	  result = -1;
	} else {
	  result = pw->pw_uid;
	}
	return(result);
}


char *error="ERROR";
char * 
l_bynum(int *argp)
{

	static char* result;
	struct passwd *pw;
	pw = getpwuid( *argp );
	if (pw==NULL) {
	  /* ERROR ! NO USER FOUND */
	  /* WE CANNOT RETURN A NULL (will screw up xdr filter) */
	  /* Point to an error string */
	  result=error;
	} else {
	  result = pw->pw_name;
	}

	return(result);
}

int main( int argc, char* argv[] ) {
  char *name;
  int uid;

  if(argc < 2) {
    printf("usage: %s name_or_uid\n", argv[0]);
    exit(1);
  }
  //host = argv[1];   no es necesario
  name = argv[1];
  if ((name[0]>='0')&&(name[0]<='9')) {
    uid = atoi(name);
    printf("UID %d, Name is %s\n",uid,l_bynum(&uid));
  } else {
    printf("Name %s, UID is %d\n",name,l_byname(name));
  }
  return(0);
}




