/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "filesystemv2.h"

bool_t
xdr_variablesLectura (XDR *xdrs, variablesLectura *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombreA, 255))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->posicionA))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantLeerA))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_variablesEscritura (XDR *xdrs, variablesEscritura *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombreA, 255))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantBytes))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->bufferEscritura, 255))
		 return FALSE;
	return TRUE;
}
