/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILESYSTEMV2_H_RPCGEN
#define _FILESYSTEMV2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct variablesLectura {
	char *nombreA;
	int posicionA;
	int cantLeerA;
};
typedef struct variablesLectura variablesLectura;

struct variablesEscritura {
	char *nombreA;
	int cantBytes;
	char *bufferEscritura;
};
typedef struct variablesEscritura variablesEscritura;

#define SERVIDORCF_PROG 0x20000001
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define LECTURA 1
extern  char ** lectura_1(variablesLectura *, CLIENT *);
extern  char ** lectura_1_svc(variablesLectura *, struct svc_req *);
#define ESCRITURA 2
extern  int * escritura_1(variablesEscritura *, CLIENT *);
extern  int * escritura_1_svc(variablesEscritura *, struct svc_req *);
extern int servidorcf_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LECTURA 1
extern  char ** lectura_1();
extern  char ** lectura_1_svc();
#define ESCRITURA 2
extern  int * escritura_1();
extern  int * escritura_1_svc();
extern int servidorcf_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_variablesLectura (XDR *, variablesLectura*);
extern  bool_t xdr_variablesEscritura (XDR *, variablesEscritura*);

#else /* K&R C */
extern bool_t xdr_variablesLectura ();
extern bool_t xdr_variablesEscritura ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILESYSTEMV2_H_RPCGEN */
