/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "filesystem.h"

struct response_H *
readfile_1_svc(struct read_H *argp, struct svc_req *rqstp)
{
	static struct response_H  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
writefile_1_svc(struct write_H *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
