/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "filesystemv2.h"

struct retorno *
lectura_1_svc(struct valoresLectura *argp, struct svc_req *rqstp)
{
	static struct retorno  result;

	FILE *archivo;
	result.bytes_leidos = 0;
	result.cant_bytes = argp->cant;
		
	/* Abrimos el archivo binario en modo lectura */
	//printf("Archivo a abrir: %s\n", argp->nombreA);
	archivo = fopen(argp->nombreA, "rb+");

	/* Si no fue posible abrir el archivo informamos un error */
	if (archivo == NULL){
		printf("Error al abrir el archivo\n");
	}
	else{ 
		/* Se pudo abrir correctamente */
		//printf("El archivo fue abierto correctamente\n");
	 	/* Posicionamos el puntero en el lugar indicado (pos) por el cliente desde el comienzo del archivo */
		fseek(archivo, argp->pos, SEEK_SET);

//		printf("Leyendo archivo...\n");
		result.bytes_leidos = fread(result.ret_bytes, sizeof(unsigned char), argp->cant, archivo);
//		printf("Cantidad leida: %d\n", 	result.bytes_leidos);
//		printf("Leido: %s\n", result.ret_bytes);
	}

	fclose(archivo);

	return &result;
}


int *
escritura_1_svc(struct valoresEscritura *argp, struct svc_req *rqstp)
{
	static int  result;

	FILE *archivo;

	/* Abrimos el archivo binario en modo append */
	printf("Archivo a abrir para escritura: %s\n", argp->nombreA);
	archivo = fopen(argp->nombreA, "ab");
	/* Si no fue posible abrir el archivo informamos un error */
	if (archivo == NULL){
		printf("Error al abrir el archivo\n");
	}
	else{ 
		/* Se pudo abrir correctamente */
		printf("Archivo para escritura abierto\n");
		/* Alocamos memoria para devolver */
		printf("Escribiendo archivo...\n");
		result = fwrite(argp->buffer, sizeof(unsigned char), argp->cant, archivo);
	}

	fclose(archivo);

	return &result;
}

