/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILESYSTEMV2_H_RPCGEN
#define _FILESYSTEMV2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STRUCT 255
#define MAX_FILE 100

struct retorno {
	u_char ret_bytes[MAX_STRUCT];
	int cant_bytes;
	int bytes_leidos;
};
typedef struct retorno retorno;

struct valoresLectura {
	char *nombreA;
	int pos;
	int cant;
};
typedef struct valoresLectura valoresLectura;

struct valoresEscritura {
	char *nombreA;
	u_char buffer[MAX_STRUCT];
	int cant;
};
typedef struct valoresEscritura valoresEscritura;

#define filesystem_prg 0x20000001
#define filesystem_ver 1

#if defined(__STDC__) || defined(__cplusplus)
#define lectura 1
extern  struct retorno * lectura_1(struct valoresLectura *, CLIENT *);
extern  struct retorno * lectura_1_svc(struct valoresLectura *, struct svc_req *);
#define escritura 2
extern  int * escritura_1(struct valoresEscritura *, CLIENT *);
extern  int * escritura_1_svc(struct valoresEscritura *, struct svc_req *);
extern int filesystem_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define lectura 1
extern  struct retorno * lectura_1();
extern  struct retorno * lectura_1_svc();
#define escritura 2
extern  int * escritura_1();
extern  int * escritura_1_svc();
extern int filesystem_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_retorno (XDR *, retorno*);
extern  bool_t xdr_valoresLectura (XDR *, valoresLectura*);
extern  bool_t xdr_valoresEscritura (XDR *, valoresEscritura*);

#else /* K&R C */
extern bool_t xdr_retorno ();
extern bool_t xdr_valoresLectura ();
extern bool_t xdr_valoresEscritura ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILESYSTEMV2_H_RPCGEN */
