/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "filesystemv2.h"

bool_t
xdr_retorno (XDR *xdrs, retorno *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->ret_bytes, MAX_STRUCT,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant_bytes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bytes_leidos))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_valoresLectura (XDR *xdrs, valoresLectura *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombreA, MAX_FILE))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pos))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_valoresEscritura (XDR *xdrs, valoresEscritura *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_string (xdrs, &objp->nombreA, MAX_FILE))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->buffer, MAX_STRUCT,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant))
		 return FALSE;
	return TRUE;
}
