/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "filesystemv2.h"


void
filesystem_prg_1(char *host, char * filename)
{
	CLIENT *clnt;
	struct retorno  *result_1;
	struct valoresLectura  lectura_1_arg;
	int  *result_2;
	struct valoresEscritura  escritura_1_arg;
	FILE * archivo_local;

#ifndef	DEBUG
	clnt = clnt_create (host, filesystem_prg, filesystem_ver, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	lectura_1_arg.nombreA = filename;	
	lectura_1_arg.pos = 0;
	lectura_1_arg.cant = 255;	
	result_1 = lectura_1(&lectura_1_arg, clnt);
	archivo_local = fopen("Archivo_local","wb");
	escritura_1_arg.nombreA= "Archivo_remoto";
	while (result_1->bytes_leidos!=0){
		fwrite(result_1->ret_bytes,sizeof(unsigned char), result_1->bytes_leidos, archivo_local);	 //Copia en el archivo local
		memcpy(escritura_1_arg.buffer,result_1->ret_bytes, result_1->bytes_leidos);
		escritura_1_arg.cant=result_1->bytes_leidos;
		result_2 = escritura_1(&escritura_1_arg,clnt);
		lectura_1_arg.pos = lectura_1_arg.pos + 255;
		result_1 = lectura_1(&lectura_1_arg, clnt);	
	}
/*	fwrite(result_1->ret_bytes,sizeof(unsigned char), result_1->bytes_leidos,archivo_local);
	escritura_1_arg.nombreA = "Copia remota";
	result_2 = escritura_1(&escritura_1_arg,clnt);*/
	if (result_1 == (struct retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}
/*	result_2 = escritura_1(&escritura_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *nombre;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	nombre = argv[2];
	filesystem_prg_1 (host, nombre);
exit (0);
}
