/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "filesystem.h"

struct response *
readfile_1_svc(struct readHeaders *argp, struct svc_req *rqstp)
{
	static struct response  result;
	FILE * file;
	result.totalBytes = argp->totalBytes;
	file = fopen(argp->fileName, "rb+");
	if (file == NULL){
		printf("Error: Can't open the file. \n");
	}	
	else{
		fseek(file, argp->position, SEEK_SET);
		result.totalBytes = fread(result.bytesReaded, sizeof(unsigned char), argp->totalBytes, file);
		

	}
	fclose(file);

	return &result;
}

int *
writefile_1_svc(struct writeHeaders *argp, struct svc_req *rqstp)
{
	static int  result;
	FILE *file;

	printf("Opening file %s\n", argp->fileName);
	file = fopen(argp->fileName, "ab");
	if (file == NULL) {
		printf("Failed opening file.");	
	} else {
		printf("Writting file..\n");
		result = fwrite(argp->buffer, sizeof(unsigned char), argp->totalBytes, file);
	}
	
	fclose(file);


	return &result;
}
