/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "filesystem.h"


void
filesystem_prg_1(char *host, char *fileName)
{
	CLIENT *clnt;
	struct response  *result_1;
	struct readHeaders  readfile_1_arg;
	int  *result_2;
	struct writeHeaders  writefile_1_arg;
	FILE * localFile;

	printf("ok11");

#ifndef	DEBUG
	clnt = clnt_create (host, filesystem_prg, filesystem_ver, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	readfile_1_arg.fileName = fileName;
	readfile_1_arg.position = 0;
	readfile_1_arg.totalBytes = 255;
	printf("ok1111");

	result_1 = readfile_1(&readfile_1_arg, clnt);
	
	/* concat .local to the filename */
	char bufferName[180];
	strcat(bufferName,fileName);
	strcat(bufferName,".local");
	localFile = fopen(bufferName, "wb");

	writefile_1_arg.fileName = fileName;
	while (result_1->totalBytes !=0 ) {
 		fwrite(result_1->bytesReaded, sizeof(unsigned char), result_1->totalBytes, localFile);	
		memcpy(writefile_1_arg.buffer, result_1->bytesReaded, result_1->totalBytes);
		writefile_1_arg.totalBytes = result_1->bytesReaded;	
		result_2 = writefile_1(&writefile_1_arg,clnt);
		readfile_1_arg.position = readfile_1_arg.position + 255;
		result_1 = readfile_1(&readfile_1_arg, clnt);
	}	

	if (result_1 == (struct response *) NULL) {
		clnt_perror (clnt, "call failed");
	}
/*
	result_2 = writefile_1(&writefile_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *fileName;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	fileName = argv[2];
	filesystem_prg_1 (host, fileName);
exit (0);
}
